# Generated by Django 4.1.7 on 2023-04-26 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[A_Z]'), django.core.validators.MaxLengthValidator(20)])),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20)),
                ('Mobile', models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[6-9]\\d{9}')])),
                ('Email', models.EmailField(max_length=254)),
                ('Aadhar', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16), django.core.validators.RegexValidator('\\d{16}')])),
            ],
        ),
    ]
