# Generated by Django 4.1.7 on 2023-04-26 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[A-Z]'), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
